// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: file.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrReq        string                 `protobuf:"bytes,1,opt,name=strReq,proto3" json:"strReq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRequest) GetStrReq() string {
	if x != nil {
		return x.StrReq
	}
	return ""
}

type TimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrResp       string                 `protobuf:"bytes,1,opt,name=strResp,proto3" json:"strResp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *TimeResponse) GetStrResp() string {
	if x != nil {
		return x.StrResp
	}
	return ""
}

type ConcatStrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrReq        string                 `protobuf:"bytes,1,opt,name=strReq,proto3" json:"strReq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatStrRequest) Reset() {
	*x = ConcatStrRequest{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatStrRequest) ProtoMessage() {}

func (x *ConcatStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatStrRequest.ProtoReflect.Descriptor instead.
func (*ConcatStrRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *ConcatStrRequest) GetStrReq() string {
	if x != nil {
		return x.StrReq
	}
	return ""
}

type ConcatStrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrReq        string                 `protobuf:"bytes,1,opt,name=strReq,proto3" json:"strReq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatStrResponse) Reset() {
	*x = ConcatStrResponse{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatStrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatStrResponse) ProtoMessage() {}

func (x *ConcatStrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatStrResponse.ProtoReflect.Descriptor instead.
func (*ConcatStrResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *ConcatStrResponse) GetStrReq() string {
	if x != nil {
		return x.StrReq
	}
	return ""
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\aapigprc\"%\n" +
	"\vTimeRequest\x12\x16\n" +
	"\x06strReq\x18\x01 \x01(\tR\x06strReq\"(\n" +
	"\fTimeResponse\x12\x18\n" +
	"\astrResp\x18\x01 \x01(\tR\astrResp\"*\n" +
	"\x10ConcatStrRequest\x12\x16\n" +
	"\x06strReq\x18\x01 \x01(\tR\x06strReq\"+\n" +
	"\x11ConcatStrResponse\x12\x16\n" +
	"\x06strReq\x18\x01 \x01(\tR\x06strReq2\x87\x01\n" +
	"\aservSrv\x128\n" +
	"\aCurTime\x12\x14.apigprc.TimeRequest\x1a\x15.apigprc.TimeResponse\"\x00\x12B\n" +
	"\tConcatStr\x12\x15.apigprc.TimeResponse\x1a\x1a.apigprc.ConcatStrResponse\"\x00(\x01B$Z\"github.com/Part001-R/grpcs/pkg/apib\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_proto_goTypes = []any{
	(*TimeRequest)(nil),       // 0: apigprc.TimeRequest
	(*TimeResponse)(nil),      // 1: apigprc.TimeResponse
	(*ConcatStrRequest)(nil),  // 2: apigprc.ConcatStrRequest
	(*ConcatStrResponse)(nil), // 3: apigprc.ConcatStrResponse
}
var file_file_proto_depIdxs = []int32{
	0, // 0: apigprc.servSrv.CurTime:input_type -> apigprc.TimeRequest
	1, // 1: apigprc.servSrv.ConcatStr:input_type -> apigprc.TimeResponse
	1, // 2: apigprc.servSrv.CurTime:output_type -> apigprc.TimeResponse
	3, // 3: apigprc.servSrv.ConcatStr:output_type -> apigprc.ConcatStrResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
